#include "tgcloud/database/encrypted_store.hpp"
#include <fstream>
#include <openssl/evp.h>
#include <random>
#include <cstring>
#include <stdexcept>
namespace tgcloud::database {
static void put(std::string& b,const std::string& s){uint32_t n=s.size();b.append((char*)&n,4);b+=s;}
static std::string get(const std::string& b,size_t& p){if(p+4>b.size())throw std::runtime_error("corrupt store");uint32_t n;memcpy(&n,b.data()+p,4);p+=4;if(p+n>b.size())throw std::runtime_error("corrupt store");auto s=b.substr(p,n);p+=n;return s;}
EncryptedFileStore::EncryptedFileStore(std::filesystem::path p,std::string pw):path_(std::move(p)),password_(std::move(pw)){load();}
void EncryptedFileStore::load(){if(!std::filesystem::exists(path_))return;std::ifstream in(path_,std::ios::binary);std::string b((std::istreambuf_iterator<char>(in)),{});if(b.size()<49||b.substr(0,5)!="TGDB1")throw std::runtime_error("invalid encrypted store");unsigned char key[32],iv[12];if(!PKCS5_PBKDF2_HMAC(password_.c_str(),password_.size(),(unsigned char*)b.data()+5,16,100000,EVP_sha256(),32,key))throw std::runtime_error("key derivation failed");memcpy(iv,b.data()+21,12);int n=b.size()-49;EVP_CIPHER_CTX*c=EVP_CIPHER_CTX_new();EVP_DecryptInit_ex(c,EVP_aes_256_gcm(),nullptr,key,iv);std::string plain(n+16,0);int out=0,fin=0;EVP_DecryptUpdate(c,(unsigned char*)plain.data(),&out,(unsigned char*)b.data()+33,n);EVP_CIPHER_CTX_ctrl(c,EVP_CTRL_GCM_SET_TAG,16,b.data()+b.size()-16);if(EVP_DecryptFinal_ex(c,(unsigned char*)plain.data()+out,&fin)<=0){EVP_CIPHER_CTX_free(c);throw std::runtime_error("authentication failed");}EVP_CIPHER_CTX_free(c);size_t p=0;uint32_t count; if(out+fin<4)throw std::runtime_error("corrupt store");memcpy(&count,plain.data(),4);p=4;for(uint32_t i=0;i<count;i++){model::CloudFile f;memcpy(&f.local_id,plain.data()+p,8);p+=8;f.file_uuid=get(plain,p);f.name=get(plain,p);f.mime_type=get(plain,p);memcpy(&f.size_bytes,plain.data()+p,8);p+=8;memcpy(&f.uploaded_at,plain.data()+p,8);p+=8;f.checksum=get(plain,p);memcpy(&f.telegram_message_id,plain.data()+p,8);p+=8;f.telegram_file_id=get(plain,p);f.telegram_file_unique_id=get(plain,p);memory_.put_file(std::move(f));}}
void EncryptedFileStore::flush() const {std::string plain;auto all=memory_.list_files((size_t)-1,0);uint32_t count=all.size();plain.append((char*)&count,4);for(auto&f:all){plain.append((char*)&f.local_id,8);put(plain,f.file_uuid);put(plain,f.name);put(plain,f.mime_type);plain.append((char*)&f.size_bytes,8);plain.append((char*)&f.uploaded_at,8);put(plain,f.checksum);plain.append((char*)&f.telegram_message_id,8);put(plain,f.telegram_file_id);put(plain,f.telegram_file_unique_id);}unsigned char salt[16],iv[12];std::random_device r;for(auto&x:salt)x=r();for(auto&x:iv)x=r();unsigned char key[32];PKCS5_PBKDF2_HMAC(password_.c_str(),password_.size(),salt,16,100000,EVP_sha256(),32,key);EVP_CIPHER_CTX*c=EVP_CIPHER_CTX_new();EVP_EncryptInit_ex(c,EVP_aes_256_gcm(),nullptr,key,iv);std::string enc(plain.size()+16,0);int out=0,fin=0;EVP_EncryptUpdate(c,(unsigned char*)enc.data(),&out,(unsigned char*)plain.data(),plain.size());EVP_EncryptFinal_ex(c,(unsigned char*)enc.data()+out,&fin);unsigned char tag[16];EVP_CIPHER_CTX_ctrl(c,EVP_CTRL_GCM_GET_TAG,16,tag);EVP_CIPHER_CTX_free(c);std::ofstream o(path_,std::ios::binary|std::ios::trunc);o.write("TGDB1",5);o.write((char*)salt,16);o.write((char*)iv,12);o.write(enc.data(),out+fin);o.write((char*)tag,16);}
}
